#! /bin/bash
function vagrant_status {
  IFS=' ' read -ra INFO_1 <<< "$(vagrant status | grep virtualbox)"
  cat << EXEC
  {
    "changed": false,
    "name": "${INFO_1[0]}"
    "state": "${INFO_1[1]}"
  }
EXEC
msg="lol"
exit code 0
}

case $state in
  started)
    vagrant_loader
  ;;
  status)
    vagrant_status
    msg="lol"
  ;;
  destroyed)
    vagrant_destroyer
  ;;
esac
msg="qwe"
printf '{"msg": "%s"}' "$msg"
exit 0
