- name: Hello playbook
  hosts: all

  tasks:
  - name: ensure apache is at the latest version
    yum: name=java state=latest
    become: yes
    become_method: sudo
  - name: Ensure that backup exist
    copy:
      backup: yes
      src: /home/student/cm/ansible/day-1/helloscript.sh
      dest: /home/vagrant/helloscript.sh
      owner: vagrant
      group: vagrant
      mode: 0776
  - name: Execute script to be ensured
    shell: /home/vagrant/helloscript.sh
  - name: Ensure helloscript.sh exist and executable
    file: 
      path: /home/vagrant/helloworld.sh
      state: absent
  - name: Ensure that student group exist
    become: yes
    become_user: root
    group:
      name: student
      state: present
  - name: Ensure that tomcat_sa group exist
    become: yes
    become_user: root
    group:
      name: tomcat_as
      state: present
  - name: Ensure that student user exist
    become: yes
    become_user: root
    user:
      name: student
      state: present
      group: student
  - name: Ensure that tomcat-sa user exist
    become: yes
    become_user: root
    user:
      name: tomcat_as
      state: present
      group: tomcat_as
  - name: Ensure that archive exist
    become: yes
    become_user: root
    get_url:
      url: http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/apache-tomcat-8.5.9.tar.gz
      dest: /home/vagrant/
      mode: 0666
      owner: tomcat_as
      group: tomcat_as
  - name: Ensure that tomcat folder will be created
    become: yes
    become_user: root
    file:
     path: /opt/tomcat/
     state: absent
  - name: Ensure that folder for tomcat exist
    become: yes
    become_user: root
    #shell: mkdir -p /opt/tomcat/ $$ chown tomcat_as:tomcat_as /opt/tomcat/
    file:
      path: /opt/tomcat/8.5.9/
      state: directory
      owner: tomcat_as
      group: tomcat_as
      mode: 0755
  - name: Ensure that tomcat will be installed from right archive
    become: yes
    become_user: root
    unarchive:
      src: /home/vagrant/apache-tomcat-8.5.9.tar.gz
      dest: /opt/tomcat/
      owner: tomcat_as
      group: tomcat_as
      remote_src: yes
  - name: Create correct tomcat folder
    become: yes
    become_user: root
    command: mv -uf /opt/tomcat/apache-tomcat-8.5.9/ /opt/tomcat/8.5.9/
  - name: Make tomcat.service correct
    become: yes
    become_user: root
    copy:
      src: /home/student/cm/ansible/day-1/tomcat.service
      dest: /usr/lib/systemd/system/tomcat.service
  - name: Execute tomcat as tomcat_as 
    become: yes
    become_method: sudo
    service:
      name: tomcat.service
      state: started
