---
# tasks file for java
# tasks:
- name: ensure that java is at the latest version
  yum: name=java state=latest
  become: yes
  become_method: sudo
- name: create fact
  become: yes
  become_user: root
  shell: java -version 2>> /etc/ansible/facts.d/java.fact
